"""Retained synthetic regression evidence for the sibling output inspector.

Run only after the successor and its runtime manifest have been approved for
testing. ATLAS_INSPECTION_TEST_ROOT must name a fresh absolute directory whose
parent already exists. Each run keeps its requests, outputs and failed checks.
No original inspector, live study artifact or calibration packet is executed.
Fixtures are generated by default. ATLAS_INSPECTION_LEGACY_FIXTURES=1 selects
the untouched historical synthetic inputs for the original acceptance case.
"""

import hashlib
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys
import traceback
import unittest
from unittest.mock import patch

from PIL import Image


REVIEW = Path("/private/tmp/atlas-v4-output-inspection-independent-review")
FIXTURES = REVIEW / "evidence/linked-resource/captured-inputs"
SYNTHETIC = Path("/private/tmp/atlas-v4-output-inspection-work/attempt-004/synthetic")
SUCCESSOR = Path(__file__).with_name("inspect_output.py")
RUN_ROOT = None
RUN_ROOT_OWNED = False
INSPECTOR = None
BEFORE = {}
FIXTURE_PATHS = {}


def reference(path):
    data = Path(path).read_bytes()
    return {
        "path": str(path),
        "sha256": hashlib.sha256(data).hexdigest(),
        "bytes": len(data),
    }


def write_json(path, value):
    with Path(path).open("x", encoding="utf8") as stream:
        json.dump(value, stream, indent=2, sort_keys=True)
        stream.write("\n")


def load_sibling(name):
    path = Path(__file__).with_name(name + ".py")
    spec = importlib.util.spec_from_file_location("atlas_inspection_" + name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError("Cannot import sibling " + name)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def setUpModule():
    global RUN_ROOT, RUN_ROOT_OWNED, INSPECTOR, BEFORE, FIXTURE_PATHS
    configured = os.environ.get("ATLAS_INSPECTION_TEST_ROOT")
    if not configured or not Path(configured).is_absolute():
        raise RuntimeError("ATLAS_INSPECTION_TEST_ROOT must be a fresh absolute path")
    RUN_ROOT = Path(configured)
    RUN_ROOT.mkdir()  # Exclusive; never merge, delete or overwrite a previous run.
    RUN_ROOT_OWNED = True
    try:
        legacy = os.environ.get("ATLAS_INSPECTION_LEGACY_FIXTURES", "0")
        if legacy not in {"0", "1"}:
            raise ValueError("ATLAS_INSPECTION_LEGACY_FIXTURES must be 0 or 1")
        if legacy == "1":
            FIXTURE_PATHS = {
                "embedded_docx": FIXTURES / "embedded.docx",
                "external_docx": FIXTURES / "external-link.docx",
                "complete_docx": SYNTHETIC / "complete.docx",
                "complete_pdf": SYNTHETIC / "complete.pdf",
                "malformed_docx": SYNTHETIC / "not-a-docx.docx",
                "xml_error_docx": SYNTHETIC / "xml-error.docx",
                "many_pages_pdf": SYNTHETIC / "too-many-pages.pdf",
                "red_image": REVIEW / "evidence/linked-resource/outside-private/private-image.png",
                "public_image": FIXTURES / "public.png",
                "visible_image": SYNTHETIC / "visible.png",
            }
            fixture_metadata = {"mode": "historical_exact_synthetic", "generatorExecuted": False}
        else:
            generator = load_sibling("synthetic_fixtures")
            FIXTURE_PATHS = generator.build_fixtures(RUN_ROOT / "fixtures")
            fixture_metadata = {
                "mode": "generated_synthetic", "generatorExecuted": True,
                "generator": reference(Path(__file__).with_name("synthetic_fixtures.py")),
                "dependencyVersions": generator.dependency_versions(),
                "determinism": "Fixed ZIP/core timestamps and invariant PDF metadata for fixed dependency versions; external DOCX URI deliberately binds this fresh fixture root.",
            }
        BEFORE = {str(path): reference(path) for path in FIXTURE_PATHS.values()}
        registration = {
            "scope": "Synthetic successor regression; no semantic qualification",
            "tests": reference(Path(__file__)),
            "successor": reference(SUCCESSOR),
            "fixtureGenerator": reference(Path(__file__).with_name("synthetic_fixtures.py")),
            "selectedTestArguments": sys.argv[1:],
            "inputs": list(BEFORE.values()),
            "fixtures": fixture_metadata,
            "fixtureBindings": {name: BEFORE[str(path)] for name, path in FIXTURE_PATHS.items()},
            "python": {"executable": sys.executable, "version": sys.version},
            "cases": [
                "embedded public DOCX renders its blue image",
                "external linked DOCX renders without outside red image",
                "complete DOCX retains both pages and object inventory",
                "complete PDF retains selectable and image-only pages",
                "missing bound capture is unavailable, not original absence",
                "wrong capture hash is unavailable",
                "malformed container retains original and failed inspection",
                "33-page PDF exceeds the declared page cap",
                "existing output directory is never overwritten",
                "XML parse failure retains partial inventory",
                "input byte cap is measurement unavailable",
                "missing renderer retains parsed evidence without fallback",
                "isolated CLI preserves bound source context and renders PDF",
            ],
            "limits": [
                "Pixel control detects the retained synthetic red canary only",
                "No generalized host-write, network or descendant proof",
                "Rendered coverage is not reviewer or semantic certification",
            ],
        }
        manifest = os.environ.get("ATLAS_INSPECTION_RUNTIME_MANIFEST")
        if manifest:
            registration["runtimeManifest"] = reference(Path(manifest))
        write_json(RUN_ROOT / "registration.json", registration)
        INSPECTOR = load_sibling("inspect_output")
    except BaseException:
        write_json(RUN_ROOT / "setup-failure.json", {"traceback": traceback.format_exc()})
        raise


def tearDownModule():
    observations = []
    for path, before in BEFORE.items():
        try:
            after = reference(Path(path))
            observations.append({"before": before, "after": after, "unchanged": before == after})
        except OSError:
            observations.append({"before": before, "unchanged": False, "traceback": traceback.format_exc()})
    write_json(RUN_ROOT / "input-readback.json", observations)
    if not all(row["unchanged"] for row in observations):
        raise AssertionError("An original synthetic input changed or became unavailable")


class InspectionTests(unittest.TestCase):
    def setUp(self):
        self.case = RUN_ROOT / self._testMethodName
        self.case.mkdir()

    def inspect(self, path, family, alter=None):
        before = reference(path)
        request = {
            "schemaVersion": 1,
            "inspectionId": self._testMethodName,
            "family": family,
            "artifact": INSPECTOR.reference(path),
            "outputRoot": str(self.case / "inspection"),
        }
        self.assertEqual(before, request["artifact"])
        if alter:
            alter(request)
        return self.run_request(request, path, before)

    def run_request(self, request, path=None, before=None):
        write_json(self.case / "request.json", request)
        try:
            result = INSPECTOR.inspect(request)
        except BaseException:
            write_json(self.case / "exception.json", {"traceback": traceback.format_exc()})
            raise
        finally:
            if path is not None:
                after = reference(path)
                write_json(self.case / "input-readback.json", {"before": before, "after": after})
                self.addCleanup(self.assertEqual, before, after)
        write_json(self.case / "result.json", result)
        self.assertIn("semanticPass", result)
        self.assertIsNone(result["semanticPass"])
        self.assertIs(result["allSourcesCertified"], False)
        return result

    def assert_pages(self, result, count):
        self.assertEqual(result["observedRenderPages"], count)
        self.assertEqual(len(result["pages"]), count)
        self.assertEqual([p["page"] for p in result["pages"]], list(range(1, count + 1)))
        for page in result["pages"]:
            self.assertIs(page["imageAvailable"], True)
            self.assertIs(page["actualReviewerInspectionRequired"], True)
            self.assertEqual(page["citation"]["kind"], "full_page_image")
            image_path = Path(page["reference"]["path"])
            self.assertTrue(image_path.is_relative_to(self.case))
            self.assertEqual(reference(image_path), page["reference"])
            with Image.open(image_path) as image:
                self.assertEqual(list(image.size), page["pixels"])
                self.assertGreater(min(image.size), 0)

    def assert_positive(self, result, pages):
        self.assertEqual(result["artifactState"], "captured")
        self.assertIs(result["inspectionMeasurementAvailable"], True)
        self.assertEqual(result["coverage"]["visual"]["state"], "complete")
        self.assertIsNone(result["coverage"]["visual"]["coversExtractionInvisibleText"])
        self.assertFalse(result["coverage"]["visual"]["reviewerInspectionPerformed"])
        self.assert_pages(result, pages)

    def pixels(self, result):
        counts = []
        for page in result["pages"]:
            with Image.open(page["reference"]["path"]) as image:
                histogram = image.convert("RGB").getcolors(image.width * image.height)
            self.assertIsNotNone(histogram)
            counts.append({
                "page": page["page"],
                "red": sum(n for n, (r, g, b) in histogram if r > 220 and g < 70 and b < 100),
                "blue": sum(n for n, (r, g, b) in histogram if r < 70 and g < 140 and b > 180),
                "image": page["reference"],
            })
        write_json(self.case / "pixel-observations.json", counts)
        return counts

    def test_embedded_public_image(self):
        result = self.inspect(FIXTURE_PATHS["embedded_docx"], "docx_report")
        self.assert_positive(result, 1)
        pixels = self.pixels(result)
        self.assertGreater(sum(p["blue"] for p in pixels), 1000)
        self.assertEqual(sum(p["red"] for p in pixels), 0)

    def test_external_image_denied_with_actual_render(self):
        result = self.inspect(FIXTURE_PATHS["external_docx"], "docx_report")
        self.assertEqual(result["artifactState"], "captured")
        self.assertIs(result["inspectionMeasurementAvailable"], False)
        # A failed/missing renderer cannot make the no-canary assertion pass.
        self.assert_pages(result, 1)
        self.assertEqual(sum(p["red"] for p in self.pixels(result)), 0)

    def test_complete_docx(self):
        result = self.inspect(FIXTURE_PATHS["complete_docx"], "docx_report")
        self.assert_positive(result, 2)
        text = "\n".join(obj.get("text", "") for obj in result["objects"])
        for value in ["Ordinary paragraph", "Nested cell content", "Synthetic running header", "Synthetic running footer", "Hidden synthetic text"]:
            self.assertIn(value, text)
        self.assertTrue(any(obj["kind"] == "image_or_media" for obj in result["objects"]))

    def test_complete_pdf(self):
        result = self.inspect(FIXTURE_PATHS["complete_pdf"], "pdf_create")
        self.assert_positive(result, 2)
        self.assertTrue(any(obj["kind"] == "page_text" and "Synthetic selectable PDF text" in obj["text"] for obj in result["objects"]))
        # This fixture has only its selectable black text in this top-page band.
        # Parser success and two valid PNGs previously hid a missing-font raster.
        with Image.open(result["pages"][0]["reference"]["path"]) as image:
            band = image.convert("RGB").crop((40, 90, 600, 155))
            dark_pixels = sum(n for n, (r, g, b) in band.getcolors(band.width * band.height) if max(r, g, b) < 128)
        write_json(self.case / "selectable-text-raster.json", {
            "page": result["pages"][0]["reference"], "regionPixels": [40, 90, 600, 155],
            "darkPixels": dark_pixels, "minimumExclusive": 300,
            "scope": "Known synthetic selectable-text region only; not a general semantic or glyph-fidelity oracle",
        })
        self.assertGreater(dark_pixels, 300, "Selectable PDF text must also be visible in the retained raster")
        self.assertTrue(any(obj["kind"] == "pdf_image" for obj in result["objects"]))
        self.assertTrue(any(obj["kind"] == "pdf_annotation" for obj in result["objects"]))
        self.assertTrue(any(obj["kind"] == "page_text" and obj["anchor"]["page"] == 2 and not obj["text"].strip() for obj in result["objects"]))

    def test_missing_capture_is_unavailable(self):
        request = {
            "schemaVersion": 1,
            "inspectionId": self._testMethodName,
            "family": "pdf_create",
            "artifact": {"path": str(self.case / "missing.pdf"), "sha256": "0" * 64, "bytes": 0},
            "outputRoot": str(self.case / "inspection"),
        }
        result = self.run_request(request)
        self.assertEqual(result["artifactState"], "unavailable")
        self.assertIs(result["inspectionMeasurementAvailable"], False)

    def test_binding_mismatch_is_unavailable(self):
        def mismatch(request):
            request["artifact"]["sha256"] = "0" * 64
        result = self.inspect(FIXTURE_PATHS["complete_pdf"], "pdf_create", mismatch)
        self.assertEqual(result["artifactState"], "unavailable")
        self.assertIs(result["inspectionMeasurementAvailable"], False)

    def test_malformed_original_retained(self):
        path = FIXTURE_PATHS["malformed_docx"]
        result = self.inspect(path, "docx_report")
        self.assertEqual(result["artifactState"], "malformed")
        self.assertIs(result["inspectionMeasurementAvailable"], False)
        self.assertEqual(result["original"]["sha256"], reference(path)["sha256"])
        self.assertTrue(any(o["stage"] == "conversion" for o in result["outcomes"]))

    def test_extra_pages_unavailable(self):
        result = self.inspect(FIXTURE_PATHS["many_pages_pdf"], "pdf_create")
        self.assertEqual(result["artifactState"], "captured")
        self.assertEqual(result["observedRenderPages"], 33)
        self.assertGreater(result["observedRenderPages"], INSPECTOR.PAGES)
        self.assertIs(result["inspectionMeasurementAvailable"], False)
        self.assertEqual(result["coverage"]["visual"]["state"], "unavailable")
        self.assertGreater(result["coverage"]["visual"]["pagesNotRasterized"], 0)

    def test_output_collision_preserves_existing_bytes(self):
        output = self.case / "inspection"
        output.mkdir()
        sentinel = output / "receipt.json"
        sentinel.write_bytes(b'{"existing":"retained"}\n')
        before = reference(sentinel)
        with self.assertRaises(FileExistsError):
            self.inspect(FIXTURE_PATHS["complete_pdf"], "pdf_create")
        self.assertEqual(reference(sentinel), before)
        self.assertEqual(sorted(p.name for p in output.iterdir()), ["receipt.json"])

    def test_xml_parse_failure_retains_inventory(self):
        result = self.inspect(FIXTURE_PATHS["xml_error_docx"], "docx_report")
        self.assertEqual(result["artifactState"], "captured")
        self.assertEqual(result["coverage"]["parser"]["state"], "unavailable")
        self.assertIs(result["inspectionMeasurementAvailable"], False)
        self.assertGreater(len(result["objects"]), 0)

    def test_input_byte_cap_is_unavailable(self):
        path = self.case / "oversize.pdf"
        with path.open("xb") as stream:
            stream.write(b"%PDF-" + b"0" * INSPECTOR.CAP)
        result = self.inspect(path, "pdf_create")
        self.assertEqual(result["artifactState"], "unavailable")
        self.assertIs(result["inspectionMeasurementAvailable"], False)
        self.assertIs(result["coverage"]["original"]["originalPathUntouched"], True)

    def test_missing_renderer_is_unavailable(self):
        unavailable = str(self.case / "unavailable-renderer")
        write_json(self.case / "test-override.json", {"BIN": unavailable, "purpose": "Missing tool only; filesystem policy is unchanged"})
        with patch.object(INSPECTOR, "BIN", unavailable):
            result = self.inspect(FIXTURE_PATHS["complete_pdf"], "pdf_create")
        self.assertEqual(result["artifactState"], "captured")
        self.assertEqual(result["coverage"]["parser"]["state"], "complete")
        self.assertEqual(result["coverage"]["visual"]["state"], "unavailable")
        self.assertIs(result["inspectionMeasurementAvailable"], False)

    def test_bound_context_cli(self):
        context = self.case / "context.json"
        write_json(context, {"schemaVersion": 1, "purpose": "Synthetic source-only context", "records": []})
        source = FIXTURE_PATHS["complete_pdf"]
        source_before = reference(source)
        context_before = reference(context)
        request = {
            "schemaVersion": 1, "inspectionId": self._testMethodName,
            "family": "pdf_create", "artifact": source_before,
            "sourceContext": context_before,
            "outputRoot": str(self.case / "inspection"),
        }
        request_path = self.case / "request.json"
        result_path = self.case / "cli-result.json"
        write_json(request_path, request)
        command = [sys.executable, "-B", str(SUCCESSOR), "--request", str(request_path), "--output", str(result_path)]
        write_json(self.case / "cli-command.json", {"command": command, "timeoutSeconds": 210})
        stdout, stderr = b"", b""
        process = {"exitCode": None, "timedOut": False}
        try:
            completed = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=210, check=False)
            stdout, stderr = completed.stdout, completed.stderr
            process["exitCode"] = completed.returncode
        except subprocess.TimeoutExpired as error:
            stdout, stderr = error.stdout or b"", error.stderr or b""
            process["timedOut"] = True
        except OSError as error:
            process.update(errorType=type(error).__name__, detail=str(error))
        finally:
            (self.case / "cli.stdout.log").write_bytes(stdout)
            (self.case / "cli.stderr.log").write_bytes(stderr)
            write_json(self.case / "cli-process.json", process)
            self.addCleanup(self.assertEqual, reference(source), source_before)
            self.addCleanup(self.assertEqual, reference(context), context_before)
        self.assertFalse(process["timedOut"])
        self.assertEqual(process["exitCode"], 0)
        result = json.loads(result_path.read_text())
        self.assert_positive(result, 2)
        self.assertIsNone(result["semanticPass"])
        self.assertIs(result["allSourcesCertified"], False)
        self.assertEqual(result["sourceContext"]["state"], "captured")
        captured_context = result["sourceContext"]["reference"]
        self.assertEqual(captured_context["sha256"], context_before["sha256"])
        self.assertEqual(captured_context["bytes"], context_before["bytes"])
        self.assertEqual(reference(Path(captured_context["path"])), captured_context)


class RetainedResult(unittest.TextTestResult):
    def stopTestRun(self):
        super().stopTestRun()
        if RUN_ROOT_OWNED:
            write_json(RUN_ROOT / "unittest-result.json", {
                "testsRun": self.testsRun,
                "successful": self.wasSuccessful(),
                "failures": [{"test": test.id(), "traceback": tb} for test, tb in self.failures],
                "errors": [{"test": test.id(), "traceback": tb} for test, tb in self.errors],
                "skipped": [{"test": test.id(), "reason": why} for test, why in self.skipped],
                "semanticQualification": False,
            })


if __name__ == "__main__":
    unittest.main(testRunner=unittest.TextTestRunner(verbosity=2, resultclass=RetainedResult))
