import { afterEach, beforeEach, expect, spyOn, test } from "bun:test";
import { existsSync, promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import ExcelJS from "exceljs";
import { OfficeConverter } from "./office-converter";

let root: string;
beforeEach(async () => {
  root = await fs.mkdtemp(path.join(tmpdir(), "atlas-office-converter-test-"));
});
afterEach(async () => {
  await fs.rm(root, { force: true, recursive: true });
});

const PDF_BYTES = Buffer.from(
  "%PDF-1.4\n1 0 obj <</Type /Page>> endobj\n%%EOF"
);

async function fixtureConverter(
  bytes = PDF_BYTES,
  format = "pdf"
): Promise<OfficeConverter> {
  const binary = path.join(root, "converter");
  await fs.writeFile(
    binary,
    `#!${process.execPath}
import {writeFileSync} from "node:fs";
import {basename, extname, join} from "node:path";
const input = process.argv.at(-1);
const format = process.argv[process.argv.indexOf("--convert-to") + 1];
if (format.split(":")[0] !== ${JSON.stringify(format)}) throw new Error("Unexpected converter format");
const output = process.argv[process.argv.indexOf("--outdir") + 1];
const filename = basename(input, extname(input)) + ${JSON.stringify(`.${format}`)};
writeFileSync(join(output, filename), Buffer.from(${JSON.stringify(bytes.toString("base64"))}, "base64"));
`,
    { mode: 0o700 }
  );
  class FixtureConverter extends OfficeConverter {
    override async resolveConverterBinary(): Promise<string> {
      return binary;
    }
  }
  return new FixtureConverter();
}

test("rejects oversized generated PDFs before reading their bytes and cleans the workspace", async () => {
  const converter = await fixtureConverter();
  const readFile = fs.readFile.bind(fs);
  const stat = fs.stat.bind(fs);
  const outputReads: string[] = [];
  let outputPath: string | undefined;
  const readSpy = spyOn(fs, "readFile").mockImplementation((...args) => {
    if (String(args[0]).endsWith(".pdf")) {
      outputReads.push(String(args[0]));
    }
    return readFile(...args);
  });
  const statSpy = spyOn(fs, "stat").mockImplementation((...args) => {
    if (String(args[0]).endsWith(".pdf")) {
      outputPath = String(args[0]);
    }
    return stat(...args);
  });
  try {
    await expect(
      converter.convertOfficeToPdf({
        buffer: Buffer.from("source"),
        filename: "input.docx",
        maxOutputBytes: PDF_BYTES.length - 1,
      })
    ).rejects.toThrow();
    expect(outputReads).toEqual([]);
    expect(outputPath).toBeDefined();
    expect(existsSync(path.dirname(outputPath!))).toBe(false);
  } finally {
    readSpy.mockRestore();
    statSpy.mockRestore();
  }
});

test("accepts generated PDFs exactly at the output limit without changing bytes", async () => {
  const converter = await fixtureConverter();
  const result = await converter.convertOfficeToPdf({
    buffer: Buffer.from("source"),
    filename: "input.docx",
    maxOutputBytes: PDF_BYTES.length,
  });
  expect(result.pdfBytes).toEqual(PDF_BYTES);
  expect(result.pageCount).toBe(1);
});

test("XLSX conversion reuses the Office worker with the Calc filter and returns a valid workbook", async () => {
  const workbook = new ExcelJS.Workbook();
  workbook.addWorksheet("Orders").addRow(["00123", 42]);
  const bytes = Buffer.from(await workbook.xlsx.writeBuffer());
  const converter = await fixtureConverter(bytes, "xlsx");
  const converted = await converter.convertOfficeToXlsx({
    buffer: Buffer.from("binary input"),
    filename: "source.xls",
    maxOutputBytes: bytes.length,
  });
  expect(converted.bytes).toEqual(bytes);
  const reopened = new ExcelJS.Workbook();
  await reopened.xlsx.load(Uint8Array.from(converted.bytes).buffer);
  expect(reopened.getWorksheet("Orders")?.getCell("A1").value).toBe("00123");
});

test("XLSX conversion rejects malformed and oversized worker output", async () => {
  const invalid = await fixtureConverter(PDF_BYTES, "xlsx");
  await expect(
    invalid.convertOfficeToXlsx({
      buffer: Buffer.from("source"),
      filename: "source.xls",
    })
  ).rejects.toThrow();
  const workbook = new ExcelJS.Workbook();
  workbook.addWorksheet("Sheet1").addRow([1]);
  const bytes = Buffer.from(await workbook.xlsx.writeBuffer());
  const oversized = await fixtureConverter(bytes, "xlsx");
  await expect(
    oversized.convertOfficeToXlsx({
      buffer: Buffer.from("source"),
      filename: "source.xlsb",
      maxOutputBytes: bytes.length - 1,
    })
  ).rejects.toThrow();
});

test("rechecks the generated bytes when output changes after its size was inspected", async () => {
  const converter = await fixtureConverter();
  const readFile = fs.readFile.bind(fs);
  const readSpy = spyOn(fs, "readFile").mockImplementation((...args) => {
    if (String(args[0]).endsWith(".pdf")) {
      return Promise.resolve(Buffer.concat([PDF_BYTES, Buffer.from("extra")]));
    }
    return readFile(...args);
  });
  try {
    await expect(
      converter.convertOfficeToPdf({
        buffer: Buffer.from("source"),
        filename: "input.docx",
        maxOutputBytes: PDF_BYTES.length,
      })
    ).rejects.toThrow();
  } finally {
    readSpy.mockRestore();
  }
});

for (const stage of ["profile", "source"] as const) {
  test(`cleans PDF conversion workspace when the initial ${stage} write fails`, async () => {
    const converter = await fixtureConverter();
    const writeFile = fs.writeFile.bind(fs);
    const failure = new Error("Simulated disk write failure");
    let workspace: string | undefined;
    const writeSpy = spyOn(fs, "writeFile").mockImplementation(
      async (...args) => {
        const filename = String(args[0]);
        const target =
          stage === "profile" ? "registrymodifications.xcu" : "input.docx";
        await writeFile(...args);
        if (path.basename(filename) === target) {
          workspace =
            stage === "source"
              ? path.dirname(filename)
              : path.dirname(path.dirname(path.dirname(filename)));
          throw failure;
        }
      }
    );
    try {
      await expect(
        converter.convertOfficeToPdf({
          buffer: Buffer.from("source"),
          filename: "input.docx",
        })
      ).rejects.toBe(failure);
      expect(workspace).toBeDefined();
      expect(existsSync(workspace!)).toBe(false);
    } finally {
      writeSpy.mockRestore();
    }
  });
}

test("cleans thumbnail workspace when writing its source fails", async () => {
  const converter = await fixtureConverter();
  const writeFile = fs.writeFile.bind(fs);
  const failure = new Error("Simulated disk write failure");
  let workspace: string | undefined;
  const writeSpy = spyOn(fs, "writeFile").mockImplementation(
    async (...args) => {
      await writeFile(...args);
      if (path.basename(String(args[0])) === "input.docx") {
        workspace = path.dirname(String(args[0]));
        throw failure;
      }
    }
  );
  try {
    await expect(
      converter.convertOfficeToPng({
        buffer: Buffer.from("source"),
        filename: "input.docx",
      })
    ).rejects.toBe(failure);
    expect(workspace).toBeDefined();
    expect(existsSync(workspace!)).toBe(false);
  } finally {
    writeSpy.mockRestore();
  }
});
