export const ARTIFACT_EDIT_MAX_FILE_BYTES = 2 * 1024 * 1024;
export const ARTIFACT_EDIT_MAX_ROWS = 500;
export const ARTIFACT_EDIT_MAX_COLUMNS = 50;
export const ARTIFACT_EDIT_MAX_CELL_BYTES = 64 * 1024;
