export const queryKeys = {
  artifacts: (profileId: string) => ["artifacts", profileId] as const,
  artifactsAll: ["artifacts-all"] as const,
  automation: (id: string) => ["automation", id] as const,
  automationRuns: (id: string) => ["automation-runs", id] as const,
  automations: ["automations"] as const,
  composioToolkits: ["composio-toolkits"] as const,
  health: ["health"] as const,
  integrations: ["integrations"] as const,
  knowledge: (profileId: string) => ["knowledge", profileId] as const,
  knowledgeAll: ["knowledge-all"] as const,
  mcp: ["mcp"] as const,
  mcpServer: (id: string) => ["mcp-server", id] as const,
  members: (orgId: string) => ["members", orgId] as const,
  models: ["models"] as const,
  orgMemory: (orgId: string) => ["org-memory", orgId] as const,
  orgMemoryProposals: (orgId: string) =>
    ["org-memory-proposals", orgId] as const,
  profile: (profileId: string) => ["profile", profileId] as const,
  profileHistory: (profileId: string) =>
    ["profile-history", profileId] as const,
  profiles: ["profiles"] as const,
  providers: ["providers"] as const,
  sessionMessages: (profileId: string, sessionId: string, orgId: string) =>
    ["session-messages", profileId, sessionId, "org", orgId] as const,
  sessions: (profileId: string) => ["sessions", profileId] as const,
  skill: (id: string) => ["skill", id] as const,
  skillProposals: (orgId: string) => ["skill-proposals", orgId] as const,
  skills: ["skills"] as const,
  soul: (profileId: string) => ["soul", profileId] as const,
  subscription: (kind: string) => ["subscription", kind] as const,
  system: ["system"] as const,
  task: (id: string) => ["task", id] as const,
  taskRuns: (id: string) => ["task-runs", id] as const,
  tasks: ["tasks"] as const,
  timezone: ["timezone"] as const,
  tool: (id: string) => ["tool", id] as const,
  tools: ["tools"] as const,
  userContext: ["user-context"] as const,
};
