from pathlib import Path
import json,hashlib,datetime
r=Path('/private/tmp/atlas-native-file-v3-c9-confirmation-health-window');life=json.loads((r/'lifecycle-projection.json').read_text());os=json.loads((r/'os-sleep-wake-projection.json').read_text())
def stamp(value):return datetime.datetime.fromisoformat(value.replace('Z','+00:00'))
start=stamp('2026-09-07T08:20:00Z');end=stamp('2026-09-07T09:20:00Z');assert all(start<=stamp(x['timestamp'])<=end for x in os['records'])
sleeps=[x for x in os['records'] if x['category']=='sleep_entry'];wakes=[x for x in os['records'] if x['category']=='wake_from_sleep'];intervals=[]
for sleep in sleeps:
 wake=next((x for x in wakes if stamp(x['timestamp'])>stamp(sleep['timestamp'])),None)
 if wake is None:continue
 duration=(stamp(wake['timestamp'])-stamp(sleep['timestamp'])).total_seconds()
 def overlap(row):
  a=datetime.datetime.fromtimestamp(row['lifecycle']['attemptStarted']['wallMs']/1000,datetime.timezone.utc);z=stamp(row['lifecycle']['at']);return max(0,(min(z,stamp(wake['timestamp']))-max(a,stamp(sleep['timestamp']))).total_seconds())
 row=max(life['rows'],key=overlap)
 intervals.append({'sleepEntryTimestamp':sleep['timestamp'],'nextWakeFromSleepTimestamp':wake['timestamp'],'entryToWakeSeconds':duration,'releasedRowWithLargestWallIntervalOverlap':row['ordinal'],'observedCallerWallMinusMonotonicSeconds':row['derivedTimingDifferencesMs']['callerWallMinusCallerMonotonic']/1000,'qualification':'Entry-to-wake categories include transition/preparation intervals; they are not exact asleep-duration counters or proof of a request-level failure cause.'})
assert len(intervals)==5
(r/'matched-clock-intervals.json').write_text(json.dumps({'method':'All five sleep_entry category records paired with the first later wake_from_sleep record; no task/quality selection','intervals':intervals},indent=2)+'\n')
lines=['# Closed health-only note: confirmation ordinals51–60','', 'The large wall/monotonic differences were already present inside the original child-process and full caller intervals. They were not introduced by later artifact grading or finalization: for rows54,55,58 and59 the total-attempt minus caller interval is only3–15ms. No task, model output, tool result, artifact, expected value, oracle or quality field was selected for this health inquiry.','', '| Closed ordinal | End UTC | Total wall seconds | Total monotonic seconds | Caller wall minus monotonic seconds | Recorded HTTP counters |','|---:|---|---:|---:|---:|---|']
for x in life['rows']:
 a=x['lifecycle'];lines.append(f"| {x['ordinal']} | {a['at']} | {a['totalAttemptElapsedWallMs']/1000:.3f} | {a['totalAttemptElapsedMs']/1000:.3f} | {x['derivedTimingDifferencesMs']['callerWallMinusCallerMonotonic']/1000:.3f} | {x['transportCounters']['httpStatusCounts']} |")
lines+=['', 'For example, row54 records950.750s total wall time and8.141s total monotonic time. Its process, caller and total wall-minus-monotonic gaps each equal about942.609s. Row55 has about909.701s caller divergence; row58 about677.696s; row59 about349.615s. Row52 has about78.779s. Row51 clocks agree within1ms, and row60 within31ms. These are comparisons of recorded clocks, not replacement attempt durations.','', 'A read-only macOS unified-log query was restricted to UTC08:20–09:20 on2026-09-07. It returned five fixed “Entering Sleep state” category matches, each followed by a “Wake from…” category match. Only timestamps and fixed event category labels were retained; raw event messages and unrelated process/app/device/reason strings were not stored or displayed.','', '| Sleep-entry category UTC | Next wake-from-sleep category UTC | Entry-to-wake seconds | Released row with greatest interval overlap | Caller clock gap seconds |','|---|---|---:|---:|---:|']
for x in intervals:lines.append(f"| {x['sleepEntryTimestamp']} | {x['nextWakeFromSleepTimestamp']} | {x['entryToWakeSeconds']:.3f} | {x['releasedRowWithLargestWallIntervalOverlap']} | {x['observedCallerWallMinusMonotonicSeconds']:.3f} |")
lines+=['', 'The correspondence supports host suspension during the observed wall/monotonic divergence. The category intervals include sleep preparation and wake transition time, so they do not equal an exact asleep-duration counter. In particular, some short work can occur after a sleep-entry log and before suspension. DarkWake, UUID and generic sleep/wake mentions are retained only as mentions and are not treated as additional certified transitions.','', 'Transport observations remain separate. Row52 records five HTTP200 responses and one recorded502 alongside one transport-error request whose upstream status is null. Rows53–57 and59 include transport-error request records with null upstream status. Row58 reports zero requests. Row60 reports five HTTP200 responses, supporting resumed successful transport within this released window; no401/403 code appears in these counters. A recorded proxy-facing502 is not evidence of an upstream provider HTTP502. This evidence does not isolate provider service, network, host suspension or another layer as the cause of an individual transport failure.','', 'No study-validity or scoring decision follows from this health note. The original full schedule, attempts, deadlines, results and later frozen analysis remain authoritative. No power setting was changed; no caffeinate process, provider call, model/test/oracle/analyzer run, cancellation, restart, source change or task-output inspection occurred. Current study execution continued independently.','', 'Bindings: lifecycle-projection.json contains10 exact original ledger-line offsets/lengths/hashes and30 immutable caller/invocation/process metadata file hashes. The active ledger as a whole is intentionally not claimed immutable. All selected lines and metadata were reread and matched before closure. os-sleep-wake-projection.json binds the exact timestamp-bounded command, exit status, captured byte count/hash and filtered timestamp/category projection; raw OS messages were discarded to honor the requested privacy boundary.','', 'The first sandboxed attempt to read log command help returned “Cannot run while sandboxed”; the permitted read-only command was then run outside that sandbox. The actual bounded OS query returned exit0. This diagnostic lookup did not affect the study.']
(r/'health-note.md').write_text('\n'.join(lines)+'\n')
for row in life['rows']:
 q=row['originalLedgerLine']
 with Path(q['path']).open('rb') as f:f.seek(q['byteOffset']);raw=f.read(q['bytes'])
 assert hashlib.sha256(raw).hexdigest()==q['sha256']
for path,binding in life['metadataBindings'].items():assert hashlib.sha256(Path(path).read_bytes()).hexdigest()==binding['sha256']
files={p.name:{'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(r.iterdir()) if p.is_file() and p.name not in ['manifest.json','closure.json']};(r/'manifest.json').write_text(json.dumps({'scope':'Closed bounded health-only exception while full confirmation remains active','files':files},indent=2)+'\n')
closure={'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'CLOSED health-only evidence; not phase closure or validity ruling','releasedClosedOrdinals':[51,60],'selectedLedgerLinesVerified':10,'selectedImmutableMetadataFilesVerified':len(life['metadataBindings']),'osWindowUTC':os['windowUTC'],'osQueryExitCode':os['returnCode'],'sleepEntryNextWakePairs':5,'noteSha256':files['health-note.md']['sha256'],'lifecycleProjectionSha256':files['lifecycle-projection.json']['sha256'],'osProjectionSha256':files['os-sleep-wake-projection.json']['sha256'],'manifestSha256':hashlib.sha256((r/'manifest.json').read_bytes()).hexdigest(),'taskModelToolArtifactOracleQualityFieldsInspected':False,'providerOrTestOrAnalyzerOrOracleCalls':0,'powerOrStudyProcessChanges':0,'sourceChanges':0};(r/'closure.json').write_text(json.dumps(closure,indent=2)+'\n');print(json.dumps({'noteSha256':closure['noteSha256'],'manifestSha256':closure['manifestSha256'],'closureSha256':hashlib.sha256((r/'closure.json').read_bytes()).hexdigest(),'intervals':intervals},indent=2))
